// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenVanCuong56022.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220322165030_Create_Table_NVC056022")]
    partial class Create_Table_NVC056022
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NguyenVanCuong56022.NVC056022", b =>
                {
                    b.Property<string>("NVCID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NVCGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NVCName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NVCID");

                    b.ToTable("NVC056022");
                });

            modelBuilder.Entity("NguyenVanCuong56022.UniversityNVC56022", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityNVC56022");
                });
#pragma warning restore 612, 618
        }
    }
}
